### ISSUE TITLE
Translate Spanish 

### ISSUE THREAD

**Issue by Dotrego** [ioc-translator/ioc-translation#4]
Maria sent us the attached file with all the translated portions for the Spanish website. They are divided by dashes+part number to be copied to the right md files.

[WEBSITE IOC ES.txt](https://github.com/ioc-translator/ioc-translation/files/813622/WEBSITE.IOC.ES.txt)

**Comment by holosphere** [comment]
Importing spanish...

**Comment by holosphere** [comment]
Spanish imported. Removed all pretty printed formatting by hand. :-/

Please edit/touch up the translation strings directly on http://github.com/ioc-translator/ioc-translation
so it can be pulled to the site without creating unneccessary hand work.

**Comment by holosphere** [comment]
Integrated all of MariaKempers pull requests.
