### ISSUE TITLE
Translate Chinese

### ISSUE THREAD

**Issue by Dotrego** [ioc-translator/ioc-translation#5]
Alicex sent us the attached file with all the translated portions for the Chinese website. They are divided by dashes+part number to be copied to the right md files. Some menu items are not translated but they are in other parts of the website, we have to fill them in manually.

[WEBSITE IOC chinese.txt](https://github.com/ioc-translator/ioc-translation/files/821335/WEBSITE.IOC.chinese.txt)

**Comment by holosphere** [comment]
Looks good, text file downloaded and will try to paste in today.

**Comment by holosphere** [comment]
Chinese hand pasted into the site the Chinese way. :1st_place_medal: 

Please edit/touch up the translation strings directly on http://github.com/ioc-translator/ioc-translation
so it can be pulled to the site without creating unneccessary hand work.

**Comment by holosphere** [comment]
I updated some hand-contributed issues, but want to make clear I expect people to work through the system and not hand every bit of editing to me. Where is our translation coordinator anyways?
